version: '3'

services:

  todofront:
    image: todofrontend
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    ports:
      - 3000:3000
    restart: always

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    restart: on-failure
